---
- name: Setup Eareeda Stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import output variable
      include_vars: vars/output_vars

    - name: Import Eereeda setup variable
      include_vars: vars/eereedastacksetup

    - name: Import VPC setup variable
      include_vars: vars/vpc_setup

    - name: Create Eereeda EC2 Key
      ec2_key:
        name: Eereeda-key-Stack
        region: "{{region}}"
      register: Eereeda_key_out

    - name: Save private Key into file Eereeda-key-Stack.pem
      copy:
        content: "{{Eereeda_key_out.key.private_key}}"
        dest: "./Eereeda-key-Stack.pem"
        mode: 0600
      when: Eereeda_key_out.changed

    - name: Create security group for Load Balancer
      ec2_group:
        name: Eereeda-LB-sg
        description: Allow port 80 from everywhere and all ports withn SG
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: EereedaELBSG_out

    - name: Create security group for Eereeda Stack
      ec2_group:
        name: Eereeda-Stack-sg
        description: Allow port 22 from everywhere and all ports withn SG
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{EereedaELBSG_out.group_id}}"

          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{BastionSGid}}"
      register: EereedaStackSG_out

    - name: Create security group with its own SG ID
      ec2_group:
        name: Eereeda-Stack-sg
        description: Allow port 22 from everywhere and all ports withn SG
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{EereedaStackSG_out.group_id}}"

    - name: Creating Nginx Web01
      ec2:
        key_name: Eereeda-key-Stack
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{nginx_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Web01"
          Project: Eereeda
          Owner: Meraj
        exact_count: 1
        count_tag:
          Name: "Web01"
          Project: Eereeda
          Owner: Meraj
        group_id: "{{EereedaStackSG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: web01_out

    - name: Creating Tomcat App01
      ec2:
        key_name: Eereeda-key-Stack
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{tomcat_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "App01"
          Project: Eereeda
          Owner: Meraj
        exact_count: 1
        count_tag:
          Name: "App01"
          Project: Eereeda
          Owner: Meraj
        group_id: "{{EereedaStackSG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: app01_out

    - name: Creating Memcache Mc01
      ec2:
        key_name: Eereeda-key-Stack
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{memcache_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Mc01"
          Project: Eereeda
          Owner: Meraj
        exact_count: 1
        count_tag:
          Name: "Mc01"
          Project: Eereeda
          Owner: Meraj
        group_id: "{{EereedaStackSG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: mc01_out

    - name: Creating RabbitMQ RMQ01
      ec2:
        key_name: Eereeda-key-Stack
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{rmq_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "RMQ01"
          Project: Eereeda
          Owner: Meraj
        exact_count: 1
        count_tag:
          Name: "RMQ01"
          Project: Eereeda
          Owner: Meraj
        group_id: "{{EereedaStackSG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: rmq01_out

    - name: Creating MySQL Db01
      ec2:
        key_name: Eereeda-key-Stack
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{mysql_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Db01"
          Project: Eereeda
          Owner: Meraj
        exact_count: 1
        count_tag:
          Name: "Db01"
          Project: Eereeda
          Owner: Meraj
        group_id: "{{EereedaStackSG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: db01_out

    - debug:
        var: db01_out
